:sparkles::construction:FirstDBConnection
AlenoJankowsky/hardware-verwaltung pull request #3
Opened 2024-09-24 06:22 UTC by xDerNico

Ersten Dateien zur Verbindung zur Datenbank.

2024-09-24 06:23 UTC, AlenoJankowsky commented
Bitte besser machen, danke

2024-09-24 13:37 UTC, xDerNico commented
Bitte dran denken, dass der Pfad hierbei **NOCH MANUELL **  Reingereicht wird. Wenn ihr das ganze testen wollt. Bitte ein erreichbaren Pfad angeben.

2024-09-24 14:36 UTC, AlenoJankowsky commented
![image](https://github.com/user-attachments/assets/c3663bcd-a50b-47be-be20-10b0a771ed22)

2024-09-24 14:48 UTC, AlenoJankowsky requested changes

2024-09-24 14:48 UTC, AlenoJankowsky commented on DBConnection/Connection.cs
> +        public bool DBConnect()
```suggestion
    { 
        public bool DBConnect()
```
Wird nicht benutzt

2024-09-24 14:48 UTC, AlenoJankowsky commented on DBConnection/Connection.cs
> +            }
```suggestion
                sqlconnection.Open();

                return true;
            }
```

Bitte darauf achten keine leeren Lines zu hinterlassen und wenn das "return" statement alleinstehen ist, dann keine Newline davor. Wenn Code davor vorhanden ist, immer leerzeile.

2024-09-24 14:48 UTC, AlenoJankowsky commented on DBConnection/Connection.cs
> +            }
```suggestion
            {
                return false;
            }
```

2024-09-24 14:48 UTC, AlenoJankowsky commented on DBConnection/Connection.cs
> +}
```suggestion
}

```

2024-09-24 14:48 UTC, AlenoJankowsky commented on DBConnection/Program.cs
> +        public static void Main(string[] args)
```suggestion
    { 
        public static void Main(string[] args)
```

2024-09-24 14:48 UTC, AlenoJankowsky commented on DBConnection/Program.cs
> +              if (oConnection.DBConnect() == true)
```suggestion
              if (oConnection.DBConnect())
```
Ein Vergleich mit myBoolean == true ist redundant, weil der Boolean an sich schon den Wahrheitswert hat 👍

2024-09-24 14:48 UTC, AlenoJankowsky commented on Logging/Program.cs
> +namespace Logging
```suggestion
using System.IO;

namespace Logging
```

2024-09-24 14:48 UTC, AlenoJankowsky commented on Logging/Program.cs
> +public class Log
Warum nicht einfach eine .cs Datei namens "Log" erstellen und die Klasse darin schreiben? Dann brauchst du auch keine Main Methode mehr 👍

2024-09-24 14:48 UTC, AlenoJankowsky commented on Logging/Program.cs
> +        if (!File.Exists(sLogPath))
```suggestion
        string sLogPath = sLogFolder + @"\" + sLogFile; 
        
        if (!File.Exists(sLogPath))
```

2024-09-24 14:48 UTC, AlenoJankowsky commented on Logging/Program.cs
> +    }
```suggestion
        }
        
        oStreamWriter = new StreamWriter(sLogPath,append: true);
    }
```

2024-09-24 14:48 UTC, AlenoJankowsky commented on Logging/Program.cs
> +}
```suggestion
    }
    }
}

```
Bitte die gesamte Einrückung der Datei nochmal überarbeiten

2024-09-24 14:52 UTC, AlenoJankowsky commented
Können wir uns darauf einigen, dass wir die geschweiften Klammern für c# dann so machen, wie du es hier gemacht hast, aber für typescript später dann so:

`if(myboolean) {
  dostuff();
}
`

2024-10-08 05:31 UTC, AlenoJankowsky approved these changes
LGTM 👍

2024-10-08 05:42 UTC, merged